[cerebrium.deployment]
name = "alex-v2-cerebrium"
python_version = "3.10"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = true
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*']

[cerebrium.dependencies.pip]
"livekit-agents" = "latest"
"livekit-plugins-silero" = "latest"
"livekit-plugins-deepgram" = "latest"
"livekit-plugins-openai" = "latest"
"livekit-plugins-cartesia" = "latest"
"python-dotenv" = "latest"
livekit-plugins-noise-cancellation = "latest"
PyYAML = "latest"

[cerebrium.dependencies.apt]
ffmpeg = "latest"

[cerebrium.hardware]
cpu = 2.0
memory = 2.0
compute = "CPU"
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 30
replica_concurrency = 1
scaling_metric = "concurrency_utilization"

[cerebrium.runtime.custom]
port = 8080
entrypoint = ["python", "main.py", "start"]

#[cerebrium.runtime.custom]
#port = 8081
#dockerfile_path = "./Dockerfile"

#[env]
#PYTHONUNBUFFERED = '1'
#LIVEKIT_AGENTS_INIT_TIMEOUT = "120"
#LIVEKIT_AGENTS_INFERENCE_ENABLED = "false"
